version: "3.7"
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./server:/app/data
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true