version: "3.7"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5173:5173"  # Backend escutando na porta 5773
    networks:
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
